// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwlAMD_HTZhdQJx3pSEhHIGKPkawdkZ9A',
    appId: '1:683703012683:web:737cea1ac050a05664acce',
    messagingSenderId: '683703012683',
    projectId: 'chat-flutter-c2a69',
    authDomain: 'chat-flutter-c2a69.firebaseapp.com',
    storageBucket: 'chat-flutter-c2a69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvP2PbMifzj1dnGLgmqtt9J8474ndGDao',
    appId: '1:683703012683:android:edb8fb7d478c019b64acce',
    messagingSenderId: '683703012683',
    projectId: 'chat-flutter-c2a69',
    storageBucket: 'chat-flutter-c2a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADauwOyabwnIVKzGWS5yOVEOpJiFq0CWU',
    appId: '1:683703012683:ios:1ba6f92393a1b3d464acce',
    messagingSenderId: '683703012683',
    projectId: 'chat-flutter-c2a69',
    storageBucket: 'chat-flutter-c2a69.appspot.com',
    androidClientId: '683703012683-irg3jakk9dc0v0p0kmdaqvn0ebd7vgp4.apps.googleusercontent.com',
    iosClientId: '683703012683-ck1ah07nh97f2mqo749l1974vt41lsbn.apps.googleusercontent.com',
    iosBundleId: 'com.petersudario.chat.flutterChatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADauwOyabwnIVKzGWS5yOVEOpJiFq0CWU',
    appId: '1:683703012683:ios:7c56c6e919c7d10364acce',
    messagingSenderId: '683703012683',
    projectId: 'chat-flutter-c2a69',
    storageBucket: 'chat-flutter-c2a69.appspot.com',
    androidClientId: '683703012683-irg3jakk9dc0v0p0kmdaqvn0ebd7vgp4.apps.googleusercontent.com',
    iosClientId: '683703012683-1j8n43466gqdo9i8d1g5o30cnel4mvro.apps.googleusercontent.com',
    iosBundleId: 'com.petersudario.chat.flutterChatFirebase.RunnerTests',
  );
}
